### ISSUE TITLE
Erro in browser console: Uncaught TypeError: Cannot read property 'X' of undefined

### ISSUE THREAD

**Issue by YuriyTimoshenkov** [YuriyTimoshenkov/Slowpoke.Net#4]
Steps to reproduce:
1. Start Cabinet
2. Login
3. Press  play button
4. Slowpoke.html is loaded

Expected result: I could play 
Real result: in browser console I've got
"undefined!!!!!!
utils.js:34 Uncaught TypeError: Cannot read property 'X' of undefined"

**Comment by dimapct** [comment]
code base changed. not relevant any more
