### ISSUE TITLE
To implement scoring system

### ISSUE THREAD

**Issue by dimapct** [YuriyTimoshenkov/Slowpoke.Net#51]

**Comment by dimapct** [comment]
agreed to display number of kills

**Comment by YuriyTimoshenkov** [comment]
Done.
Now you could visualize PlayerBody.Score value on user browser view.

**Comment by YuriyTimoshenkov** [comment]
Please, implement usable visualization.
Current mini text is not clear.
My proposition is to
- place all indicator on the bottom left corner
- use labels for each(Score: XXXX)

**Comment by dimapct** [comment]
fixed
