### ISSUE TITLE
To impelement path finding logic (Algorithm A*)

### ISSUE THREAD

**Issue by dimapct** [YuriyTimoshenkov/Slowpoke.Net#81]
Requirement:
To implement path finding algorithm Li for NPC.

**Comment by mungobungo** [comment]
Use A* algorithm. Lee is the most basic one. And don't have perks as "tuning weight of nodes" and other funky stuff as A* has.

https://www.youtube.com/watch?v=QWLIWr9V7dQ

https://www.youtube.com/watch?v=nGC_kBCoHYc

All the cool guys (Starcraft for example) uses A* or its modifications. Be cool. Be star. A Star.

**Comment by dimapct** [comment]
thank you, taken into consideration)

**Comment by dimapct** [comment]
duplicate, see issue 
https://github.com/YuriyTimoshenkov/Slowpoke.Net/issues/155
