### ISSUE TITLE
to standardize js constructor naming convention

### ISSUE THREAD

**Issue by dimapct** [YuriyTimoshenkov/Slowpoke.Net#9]
we use different naming conventions. E. g. constructor names:
Yura:
function viewManagerFactory

Dima:
function GameMap

**Comment by YuriyTimoshenkov** [comment]
I'm  using this one http://www.w3schools.com/js/js_conventions.asp and suggest you would too

**Comment by dimapct** [comment]
In this article there are nothing said about the naming convention for class constructors. 
Constructors should be written with the first capital letter: 
function ConstructorOfAClass () {}
I've took this standard from o`Reilly's
